//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C.MpesaServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api-v1.gen.mm.vodafone.com/mminterface/request", ConfigurationName="MpesaServiceRef.RequestMgrPortType")]
    public interface RequestMgrPortType {
        
        // CODEGEN: Generating message contract since the operation GenericAPIRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2C.MpesaServiceRef.GenericAPIRequestResponse GenericAPIRequest(B2C.MpesaServiceRef.GenericAPIRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<B2C.MpesaServiceRef.GenericAPIRequestResponse> GenericAPIRequestAsync(B2C.MpesaServiceRef.GenericAPIRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com.cn/schema/common/v2_1")]
    public partial class RequestSOAPHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string spIdField;
        
        private string spPasswordField;
        
        private string serviceIdField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string spId {
            get {
                return this.spIdField;
            }
            set {
                this.spIdField = value;
                this.RaisePropertyChanged("spId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string spPassword {
            get {
                return this.spPasswordField;
            }
            set {
                this.spPasswordField = value;
                this.RaisePropertyChanged("spPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenericAPIRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.huawei.com.cn/schema/common/v2_1")]
        public B2C.MpesaServiceRef.RequestSOAPHeader RequestSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api-v1.gen.mm.vodafone.com/mminterface/request", Order=0)]
        public string RequestMsg;
        
        public GenericAPIRequestRequest() {
        }
        
        public GenericAPIRequestRequest(B2C.MpesaServiceRef.RequestSOAPHeader RequestSOAPHeader, string RequestMsg) {
            this.RequestSOAPHeader = RequestSOAPHeader;
            this.RequestMsg = RequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenericAPIRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api-v1.gen.mm.vodafone.com/mminterface/request", Order=0)]
        public string ResponseMsg;
        
        public GenericAPIRequestResponse() {
        }
        
        public GenericAPIRequestResponse(string ResponseMsg) {
            this.ResponseMsg = ResponseMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequestMgrPortTypeChannel : B2C.MpesaServiceRef.RequestMgrPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestMgrPortTypeClient : System.ServiceModel.ClientBase<B2C.MpesaServiceRef.RequestMgrPortType>, B2C.MpesaServiceRef.RequestMgrPortType {
        
        public RequestMgrPortTypeClient() {
        }
        
        public RequestMgrPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestMgrPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestMgrPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestMgrPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2C.MpesaServiceRef.GenericAPIRequestResponse B2C.MpesaServiceRef.RequestMgrPortType.GenericAPIRequest(B2C.MpesaServiceRef.GenericAPIRequestRequest request) {
            return base.Channel.GenericAPIRequest(request);
        }
        
        public string GenericAPIRequest(B2C.MpesaServiceRef.RequestSOAPHeader RequestSOAPHeader, string RequestMsg) {
            B2C.MpesaServiceRef.GenericAPIRequestRequest inValue = new B2C.MpesaServiceRef.GenericAPIRequestRequest();
            inValue.RequestSOAPHeader = RequestSOAPHeader;
            inValue.RequestMsg = RequestMsg;
            B2C.MpesaServiceRef.GenericAPIRequestResponse retVal = ((B2C.MpesaServiceRef.RequestMgrPortType)(this)).GenericAPIRequest(inValue);
            return retVal.ResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2C.MpesaServiceRef.GenericAPIRequestResponse> B2C.MpesaServiceRef.RequestMgrPortType.GenericAPIRequestAsync(B2C.MpesaServiceRef.GenericAPIRequestRequest request) {
            return base.Channel.GenericAPIRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2C.MpesaServiceRef.GenericAPIRequestResponse> GenericAPIRequestAsync(B2C.MpesaServiceRef.RequestSOAPHeader RequestSOAPHeader, string RequestMsg) {
            B2C.MpesaServiceRef.GenericAPIRequestRequest inValue = new B2C.MpesaServiceRef.GenericAPIRequestRequest();
            inValue.RequestSOAPHeader = RequestSOAPHeader;
            inValue.RequestMsg = RequestMsg;
            return ((B2C.MpesaServiceRef.RequestMgrPortType)(this)).GenericAPIRequestAsync(inValue);
        }
    }
}
