//====================================================================================================
// Code generated with Velocity: SL Gen (Build 2.4.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 09/02/2013 13:05:47 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ServiceModel;
using fMessagingSystem.Entities;

namespace fMessagingSystem.Services.Contracts
{
    /// <summary>
    /// Service contract for MessagingService.
    /// </summary>


    [ServiceContract]
    [ServiceKnownType(typeof(EmailMessage))]
    [ServiceKnownType(typeof(SMSMessage))]
    public interface IMessagingService
    {

        #region Generic mesages

        [OperationContract]
        void SendListMessage(List<Message> ms);

        [OperationContract]
        void SendMessage(Message m);

        #endregion

        #region SMS
        [OperationContract]
        void SendSms(string message, string addressTo);

        [OperationContract]
        void SendSMSMessage(SMSMessage message);

         

        #endregion

        #region Email
        [OperationContract]
        void SendEmailMessage(EmailMessage message);

        [OperationContract]
        void SendEmail(string addressTo, string Body);

        [OperationContract]
        void SendEmailExt(string addressTo, string addressFrom, string subject, string Body);

        #endregion

        #region Simcard reader
        [OperationContract]
        void ReadMessageFromModem();
        #endregion
    }
}