//====================================================================================================
// Code generated with Motion: BC Gen (Build 2.2.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 08/11/2013 18:01:17 
//====================================================================================================

using fMessagingSystem.Data;
using fMessagingSystem.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Mail;
using System.Threading;
using fCommon.Utility;

namespace fMessagingSystem.Business
{
    /// <summary>
    /// Email business component.
    /// </summary>
    public partial class EmailComponent
    {
        //incoming emails settings
        string POP3Server = "mail.softwareproviders.co.ke";
        int POP3Port = 110;

        //outgoing emails settingsg
        string SMTPServer = "mail.softwareproviders.co.ke";
        string addressFrom = "info@softwareproviders.co.ke";
        string defaulSubject = "Fanikiwa Message";
        int SMTPPort = 587;
        int TimeOut = 500000;

        //credentials
        string username = "fmuraya";
        string pwd = "fmuraya";

        bool mailSent = false;

        public EmailComponent()
        {
            //read these variables from a configuration file
            POP3Server = "mail.softwareproviders.co.ke";
            POP3Port = 110;

            //outgoing emails settings
            SMTPServer = "mail.softwareproviders.co.ke";
            SMTPPort = 587;
            TimeOut = 500000;
        }

        public void SendMessage(EmailMessage message)
        {
            this.SendMessage(message.addressTo, message.addressFrom, message.subject, message.body.ToString());
        }

        public void SendMessage(string addressTo, string addressFrom, string subject, string Body)
        {
            SendMessage(new List<string>() { addressTo }, addressFrom, subject, Body);
        }
        public void SendMessage(string addressTo, string Body)
        {
            SendMessage(addressTo, addressFrom, defaulSubject, Body);
        }

        //basic email sending code
        public void SendMessage(List<string> addressTo, string addressFrom, string subject, string Body)
        {
            System.Net.Mail.MailMessage message = new System.Net.Mail.MailMessage();
            foreach (string address in addressTo)
            {
                message.To.Add(address);
            }
            message.Subject = subject;
            message.From = new System.Net.Mail.MailAddress(addressFrom);
            message.Body = Body;
            message.ReplyToList.Add(addressFrom);

            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient();
            smtp.UseDefaultCredentials = false;
            System.Net.NetworkCredential NetworkCred = new System.Net.NetworkCredential();
            NetworkCred.UserName = Config.GetString("UserName");
            NetworkCred.Password = Config.GetString("Password");
            smtp.Credentials = NetworkCred;
            smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
            smtp.Host = Config.GetString("Host");
            smtp.EnableSsl = Config.GetBool("EnableSsl");
            smtp.Port = Config.GetInt("Port");
            smtp.Timeout = Config.GetInt("Timeout");
            smtp.Send(message);

            Thread.Sleep(Config.GetInt("ThreadSleep"));
            smtp.Send(message);
        }

        //basic email sending code
        public void SendMessage(string addressTo, string addressFrom, string subject, string Body, int TimeOut)
        {
            System.Net.Mail.MailMessage message = new System.Net.Mail.MailMessage();
            MailAddress _addressTo = new MailAddress(addressTo);
            message.To.Add(_addressTo);
            message.Subject = subject;
            message.From = new System.Net.Mail.MailAddress(Config.GetString("AddressFrom"));
            message.Body = Body;
            //message.ReplyToList.Add(addressFrom); 
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient();
            smtp.UseDefaultCredentials = false;
            System.Net.NetworkCredential NetworkCred = new System.Net.NetworkCredential();
            NetworkCred.UserName = Config.GetString("UserName");
            NetworkCred.Password = Config.GetString("Password");
            smtp.Credentials = NetworkCred;
            smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
            smtp.Host = Config.GetString("Host");
            smtp.EnableSsl = Config.GetBool("EnableSsl");
            smtp.Port = Config.GetInt("Port");
            smtp.Timeout = Config.GetInt("Timeout");
            smtp.Send(message);

            Thread.Sleep(Config.GetInt("ThreadSleep"));
            smtp.Send(message);
        }



    }
}