//====================================================================================================
// Code generated with Motion: BC Gen (Build 2.2.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 08/11/2013 18:28:21 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using fMessagingSystem.Entities;
using fMessagingSystem.Data;


namespace fMessagingSystem.Business
{
    /// <summary>
    /// WebMessage business component.
    /// </summary>
    public partial class WebMessageComponent
    {
        //incoming emails settings
        string POP3Server = "mail.softwareproviders.co.ke";
        int POP3Port = 110;

        //outgoing emails settings
        string SMTPServer = "mail.softwareproviders.co.ke";
        int SMTPPort = 587;

        public WebMessageComponent()
        {

        }
        /// <summary>
        /// SendMessage business method. 
        /// </summary>
        /// <param name="errorCode">A errorCode value.</param>
        public void SendMessage(WebMail message)
        {
            this.SendMessage(message.addressTo, message.addressFrom, message.subject, message.body.ToString(), SMTPServer);

        }
        public void SendMessage(string addressTo, string addressFrom, string subject, string Body, string smtpClient)
        {
            System.Net.Mail.MailMessage message = new System.Net.Mail.MailMessage();
            message.To.Add(addressTo);
            message.Subject = subject;
            message.From = new System.Net.Mail.MailAddress(addressFrom);
            message.Body = Body;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient(smtpClient);
            smtp.Send(message);
        }
    }
}
