//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 08/11/2013 16:32:32 
//====================================================================================================

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace fMessagingSystem.Entities
{
    [Serializable]
    [DataContract]
    public partial class InformMessage
    {
        [DataMember]
        [Browsable(false)]
        public int Id { get; set; }

        [DataMember]
        [Display(Name = "Address From")]
        public string AddressFrom { get; set; }

        [DataMember]
        [Display(Name = "Address To")]
        public string AddressTo { get; set; }

        [DataMember]
        [Display(Name = "Message Date")]
        public DateTime MessageDate { get; set; }

        [DataMember]
        [Display(Name = "Body")]
        public string Body { get; set; }

        [DataMember]
        [Display(Name = "Status")]
        public string Status { get; set; }

        [DataMember]
        [Display(Name = "Message Type")]
        public string MessageType { get; set; }

        [DataMember]
        [Display(Name = "Message Inform Type")]
        public string MessageInformType { get; set; }

        [DataMember]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

    }

   

}