//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 08/11/2013 16:32:32 
//====================================================================================================

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace fMessagingSystem.Entities
{
    /// <summary>
    /// Represents a row of GSMMessage data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class MpesaMessage
    { 
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MessageBody column.
        /// </summary>
        [DataMember]
        [Display(Name = "Message Body")]
        public object MessageBody { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Storage column.
        /// </summary>
        [DataMember]
        [Display(Name = "Storage")]
        public string Storage { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        [Display(Name = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserDataText column.
        /// </summary>
        [DataMember]
        [Display(Name = "User Data Text")]
        public string UserDataText { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SmscAddressType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Address Type")]
        public string SmscAddressType { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SmscAddress column.
        /// </summary>
        [DataMember]
        [Display(Name = "Address")]
        public string SmscAddress { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SCTimestamp column.
        /// </summary>
        [DataMember]
        [Display(Name = "Time stamp")]
        public string SCTimestamp { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OriginatingAddressType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Originating Address Type")]
        public string OriginatingAddressType { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OriginatingAddress column.
        /// </summary>
        [DataMember]
        [Display(Name = "Originating Address")]
        public string OriginatingAddress { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MessageType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Message Type")]
        public string MessageType { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MessageIndex column.
        /// </summary>
        [DataMember]
        [Display(Name = "Message Index")]
        public string MessageIndex { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MessageIndex column.
        /// </summary>
        [DataMember]
        [Display(Name = "Message Status")]
        public string MessageStatus { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Processed column.
        /// </summary>
        [DataMember]
        [Display(Name = "Processed")]
        public bool Processed { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        [Display(Name = "IsDeleted")]
        public bool IsDeleted { get; set; }

        [DataMember]
        [Display(Name = "Mpesa Amount")]
        public decimal MpesaAmount { get; set; }

        [DataMember]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [DataMember]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [DataMember]
        [Display(Name = "Phone Number")]
        public string PhoneNo { get; set; }

        [DataMember]
        [Display(Name = "Date Sent")]
        public string DateSent { get; set; }

        [DataMember]
        [Display(Name = "Date Received")]
        public string DateReceived { get; set; }

        [DataMember]
        [Display(Name = "Mpesa Balance")]
        public decimal MpesaBalance { get; set; }

        [DataMember]
        [Display(Name = "Time Sent")]
        public string TimeSent { get; set; }

        [DataMember]
        [Display(Name = "AMPM")]
        public string AmPm { get; set; }

        [DataMember]
        [Display(Name = "Receipt Number")]
        public string ReceiptNumber { get; set; }

        [DataMember]
        [Display(Name = "IsMpesaDepositMessage")]
        public bool IsMpesaDepositMessage { get; set; }
         
    }
}
